### PR TITLE
added a requirements file

### PR DESCRIPTION
**Pull request by teroz**
Changes to be committed:
	new file:   requirements.txt

### CODE REVIEW

**Comment by teroz** [comment]
latest keras breaks the app

**Comment by PiSimo** [comment]
keras (2.1.3) ?

**Comment by teroz** [comment]
that's correct @PiSimo Keras 2.1.3 is the latest version

**Comment by PiSimo** [comment]
I've updated it to 2.1.3 and it worked fine

**Comment by teroz** [comment]
I got this issue when training though the run would work fine (but from a clean install though).
[AttributeError: 'list' object has no attribute 'ndim'](https://github.com/PiSimo/BitcoinForecast/issues/11)

**Pull request merged**
